spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: service_customer
          uri: http://localhost:8084
          order: 0
          predicates:
          - Path=/feign/**
          filters:
          - StripPrefix=1
          - AddResponseHeader=X-Response-Default-Foo, Default-Bar


server:
  port: 8087